export enum Dominios {
	TIEMPO_PRESCRIPCION = "TMPPRESC",
	TIPO_VEHICULO = "TIPVH",
	CANTIDAD_RUEDAS = "RUEDA",
	CILINDRAJE = "CILIN",
	TIPOS_CONCEPTO = "TPCONCEP", // Debito o credito
	DOCUMENTO_NORMATIVA ="DOCNORM"
}
