export const PARAMETRO_TIPO_CALENDARIO = 'TIPO_CALENDARIO';
export const DOMINIO_TIPO_CALENDARIO = 'TIPO_CAL';
export const TIPO_CALENDARIO_DIA_CALENDARIO = 'DIA_CAL';
export const TIPO_CALENDARIO_DIA_HABIL = 'DIA_HAB';
export const CONCEPTO_TIPOLOGIA_DEBITO = 'CONDEB';
export const CONCEPTO_TIPOLOGIA_CREDITO = 'CONCRED';